google/budoux

budoux/__init__.py, budoux/main.py, setup.cfg
I have made better the way to loading current version of project. It shares version info to `setup.cfg` and `budoux/main.py`. 
When you would like to update projects version, please modify the version in `budoux/__init__.py`.
=> Fix version data

.github/workflows/nodejs-unittest.yml
To test cli in npm, I added `npm link` to CI.
ref: #20 & [its run](https://github.com/google/budoux/actions/runs/1514797795)
=> Add `npm link` to test CI

budoux/__init__.py, budoux/main.py, budoux/parser.py, tests/test_main.py
Change-Id: Id0a4cdd227fa40961688abe3b5611a7f61144559
=> Add thres arg to Python CLI

.gitignore, budoux/main.py, tests/test_main.py
```shellsession
$ budoux -h
usage: budoux [-h] [-H] [-m JSON] [-d STR] [-t THRES] [-V] [TXT]
BudouX is the successor to Budou,
the machine learning powered line break organizer tool.
positional arguments:
TXT                      text (default: None)
optional arguments:
-h, --help               show this help message and exit
-H, --html               HTML mode (default: False)
-m JSON, --model JSON    custom model file path (default: /Users/eggplants/prog/budoux/budoux/models/ja-knbc.json)
-d STR, --delim STR      output delimiter in TEXT mode (default: ---)
-t THRES, --thres THRES  threshold value to separate chunks (default: 1000)
-V, --version            show program's version number and exit
```
=> Add custom help formatter and shorthand of `--thres`

setup.cfg
I have added a specifier of Python required version. (`>= 3.7`)
=> Specify python required version

scripts/train.py
I'm building BudouX custom model by using own large data. However the process was killed because of out of memory issue.
```
numpy.core._exceptions.MemoryError: Unable to allocate 23.6 GiB for an array with shape (146516, 21604) and data type float64
```
I found the cause of the error was due to the following calculation of training error. Numpy allocated a large amount of memory which was beyond the capacity of the machine, when multiplying matrices.
```
res: npt.NDArray[np.float64] = w.dot(Y_train[:, None] ^ X_train) / w.sum()
```
https://github.com/google/budoux/blob/main/scripts/train.py#L150
My idea is to split the matrix into chunks so that it can allocate small memory without crash.
Before
After (L is chunk size, M is the number of chunks)
A small difference in training error was …
=> Add chunk-size option to reduce memory for model training

scripts/train.py, setup.cfg, tests/test_train.py
Take out the `split_dataset` call from the `fit` function to remove randomness from that, which will make the tests more reliable.
=> Take split_dataset out from fit

.gitignore, README.md, budoux/feature_extractor.py, budoux/main.py, budoux/parser.py, javascript/README.md, tests/test_feature_extractor.py, tests/test_main.py, tests/test_parser.py
I have added `-l`, `--lang` option to select a model by a language code.
---
```shellsession
$ budoux -l aa
usage: budoux [-h] [-H] [-m JSON | -l LANG] [-d STR] [-t THRES] [-V] [TXT]
budoux: error: argument -l/--lang: 'aa' does not exist in builtin models. (supported languages: ['zh', 'ja'])
$ budoux -l zh 今天天气晴朗。
今天天气
晴朗。
$ budoux -l ja -m budoux/models/ja-knbc.json 今日はいい天気ですね。
usage: budoux [-h] [-H] [-m JSON | -l LANG] [-d STR] [-t THRES] [-V] [TXT]
budoux: error: argument -m/--model: not allowed with argument -l/--lang
```
=> `--lang` option

javascript/README.md, javascript/src/html_processor.ts, javascript/src/parser.ts, javascript/tests/test_html_processor.ts
This patch changes `Parser.applyElement` to call the `HTMLProcessor` class.
The `HTMLProcessorOptions.separator` is changed to accept a `Node`. This is because `undefined` had double meanings; i.e., use the default (ZWSP) and use the `<wbr>` element.
=> Change `applyElement` to call `HTMLProcessor`

MANIFEST.in
The budoux source code contains type hints, but the following error occurs when using mypy.
```shell
$ cat main.py
import budoux
parser = budoux.load_default_japanese_parser()
$ mypy main.py
main.py:1: error: Skipping analyzing "budoux": module is installed, but missing library stubs or py.typed marker
main.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 source file)
```
I added `py.typed` file according to the [URL](https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports) in the error message above.  After adding the file, the error no longer occurs as shown below.
```shell
$ mypy main.py
Success: no issues found in 1 source file
```
=> Add py.typed for static analysis with mypy

javascript/src/index.ts
Hi, I was experimenting with the library and wanted to do something with the HTMLProcessor as described 
[here](https://github.com/google/budoux/tree/main/javascript#applying-to-an-html-element)
However, it would not let me import and I believe it's because there is a missing export statement from `index.ts`.
Hence I added an extra line in.
=> Add missing export for HTMLProcessor in index.ts

README.md, budoux/html_processor.py, java/README.md, java/src/main/java/com/google/budoux/HTMLProcessor.java, java/src/test/java/com/google/budoux/HTMLProcessorTest.java, java/src/test/java/com/google/budoux/ParserTest.java, javascript/README.md, javascript/src/dom.ts, javascript/src/html_processor.ts, javascript/src/tests/test_cli.ts, javascript/src/tests/test_parser.ts, tests/test_html_processor.py, tests/test_main.py, tests/test_parser.py
Replace all `overflow-wrap: break-word;` with `overflow-wrap: anywhere;`
- #143
=> Use overflow-wrap: anywhere; instead of overflow-wrap: break-word;

scripts/tests/test_train.py, scripts/train.py
Allow users to pass the validation dataset separately, instead of splitting the dataset inside the training script.
=> Add validation data arg to train.py

.gitignore, demo/package-lock.json, demo/package.json, demo/src/app.ts, demo/src/worker.ts, javascript/package.json, javascript/src/cli.ts, javascript/src/html_processor.ts, javascript/src/index.ts, javascript/src/parser.ts, javascript/src/tests/test_cli.ts, javascript/src/tests/test_html_processor.ts, javascript/src/tests/test_parser.ts, javascript/src/tests/test_webcomponents.ts, javascript/src/webcomponents/budoux-base.ts, javascript/src/webcomponents/budoux-ja.ts, javascript/src/webcomponents/budoux-zh-hans.ts
Fix #158 
This change separates HTML processing from `Parser` as the `HTMLProcessing` mixin. With this change, users can use the base parser under the environment that has no `window` reference. Refer to demo/src/worker.ts for the Web Worker usage.
Also, this changes adds the `sideEffects` field to `package.json` to make sure that the bundlers shake off unused HTML processing part of code.
=> Separate HTML processing as a mixin

javascript/src/html_processor.ts, javascript/src/parser.ts
This patch adds `Parser.parseBoundaries`, which returns a list of boundaries instead of phrases as strings. `Parser.parse` is changed to call this function.
Before this chagne, the `HTMLProcessor` computes the list of boudaries from the list of phrase strings. This chagne makes it more efficient by not computing substrings. Also, `Parser.parse` is slightly more efficient by computing substrings instead of adding one character at a time.
This patch has no behavior changes to existing functions.
=> Add `Parser.parseBoundaries` for JavaScript

javascript/src/html_processor.ts, javascript/src/tests/test_html_processor.ts
This patch supports non-breaking content in the JavaScript `HTMLProcessor`. The non-breaking content provides context for the `Parser` but the content is not breakable.
Contents with `white-space: nowrap` and `white-spce: pre` are handled as non-breaking content. The `<nobr>` element is also supported; this is useful for disconnected tree when all styles including `white-space` are not computed.
=> Support non-breaking content (`<nobr>` and `white-space: nowrap`)

scripts/encode_data.py, scripts/prepare_knbc.py, scripts/tests/test_encode_data.py
With this change, users don't need to run `pip install budoux` to run the scripts under the `scripts` directory anymore.
=> Make scripts run without install

budoux/skip_nodes.json, java/src/main/java/com/google/budoux/HTMLProcessor.java, java/src/test/java/com/google/budoux/HTMLProcessorTest.java
This patch supports non-breaking content in Java.
In Java and Python implementations, the "Skip" operation includes the skipped content to the BudouX parser, so no changes to the text for the parser is needed.
This patch changes following items:
1. Add `NOBR` to the "skip" element.
2. Fix "skip" is applied only to its descendants. Before this patch, all content following "skip" elements are skipped.
3. When there's a phrase boundary right before the "skip" element, insert a break before the "skip" element.
=> Support non-breaking content in java

budoux/html_processor.py, tests/test_html_processor.py, tests/test_parser.py
This patch supports non-breaking content in Python.
In Java and Python implementations, the "Skip" operation includes the skipped content to the BudouX parser, so no changes to the text for the parser is needed.
This patch changes following items:
1. Changed `to_skip` to a stack of elements, rather than always reset to `False` at the end of an element.
2. When there's a phrase boundary right before the "skip" element, insert a break before the "skip" element.
Note `<NOBR>` is added to `skip_nodes.json` at: https://github.com/google/budoux/pull/248.
=> Support non-breaking content in Python

javascript/src/html_processor.ts, javascript/src/parser.ts
Move hasChildTextNode from Parser to HTML Processor because HTML Processor is the only user of the static method.
=> Move hasChildTextNode to HTML Processor

budoux/html_processor.py, demo/src/app.ts, java/src/main/java/com/google/budoux/HTMLProcessor.java, java/src/main/java/com/google/budoux/Parser.java, java/src/test/java/com/google/budoux/HTMLProcessorTest.java, java/src/test/java/com/google/budoux/ParserTest.java, javascript/src/html_processor.ts, javascript/src/tests/test_cli.ts, javascript/src/tests/test_html_processor.ts, tests/test_html_processor.py, tests/test_main.py, tests/test_parser.py
This changes the default separator from WBR to ZWSP.
We observed that some screen readers split their text focus by chunks because of the inserted WBR elements. We also considered adding the `aria-hidden="true"` attribute to the WBR elements as a workaround, but the behavior was still not ideal and stable. On the other hand, the ZWSP approach does not split the text focus and works better because it does not alter the DOM tree structure. Considering that, I suggest to use ZWSP as the default separator for accessibility improvement.
Users can still use WBR tags if it's preferred by specifying the separator element.
```typescript
import {jaModel, HTMLProcessingParser} from 'budoux';
const parser = HTMLProcessingParser(jaModel, {separator: document.createElement('wbr')});
```
=> Use ZWSP instead of WBR

demo/src/app.ts, javascript/README.md, javascript/src/html_processor.ts, javascript/src/tests/test_html_processor.ts, javascript/src/tests/test_webcomponents.ts
Rename `applyElement` to `applyToElement` to make it align with `HTMLProcessor`'s API and avoid confusion. (It will apply the change **to** the element, but not apply the element to something else.)
=> Rename applyElement to applyToElement

scripts/tests/test_train.py, scripts/train.py
Update the training script to accept weights for samples.
Previously, the input data should have been formatted with -1 and 1 in the first column, indicating whether each sample is positive or negative.
```text
1	a	b	c
-1	d	e	f
1	g	h	i	j
```
With this change, the first column can now contain any integer, with the absolute value of each integer representing the weight for the corresponding sample.
```text
2	a	b	c
-3	d	e	f
5	g	h	i	j
```
This is useful when you want to train a model prioritizing a specific subset of the training dataset.
=> Support weighted samples

budoux/html_processor.py, tests/test_html_processor.py
https://github.com/google/budoux/pull/251 assumed that all tags are closed properly.
This assumption doesn't stand for cases like:
1. Self-closing tags such as `<img>` don't have corresponding close tags.
2. Unpaired close tags are still valid HTML.
This patch supports these cases by assuming all open tags that doesn't nest correctly or that doesn't close are automatically closed.
This isn't the full HTML "adoption agency algorithm", but it should be good enough for the needs of BudouX.
Fixes #355
=> Fix unpaired close tags and self-closing tags

.github/workflows/style-check.yml, java/src/main/java/com/google/budoux/HTMLProcessor.java, java/src/test/java/com/google/budoux/HTMLProcessorTest.java
This patch changes Java `HTMLProcessor` not to emit close tags if the tag is self-closing.
Also adds tests for:
* Unpaired close tags.
* Self-closing tags don't affect skip nodes (e.g., `<nobr>`.)
These test cases are from #355.
Fixes #361.
=> [Java] Stop emitting close tags if self-closing

java/src/main/java/com/google/budoux/HTMLProcessor.java
This patch replaces `wholeText()` implemented in https://github.com/google/budoux/pull/367 by a subclass of `NodeVisitor`.
Whether the `wholeText()` emits `\n` for `<br>` depends on the jsoup versions. To ensure that `getText()` always matches what `resolve()` does, this patch changes to its own logic.
=> [java] Replace `wholeText()` with `NodeVisitor`

scripts/encode_data.py, scripts/tests/test_encode_data.py
This is a follow-up change for #358, which makes it easy to output weighted samples by specifying the scale as an argument for `encode_data.py`.
=> Add the scale argument to encode_data.py

scripts/prepare_knbc.py, scripts/tests/test_prepare_knbc.py
Now users can control the granularity of chunks to be generated from the KNBC corpus with the `granularity` arg.
```bash
python scripts/prepare_knbc.py KNBC_v1.0_090925_utf8 --granularity=phrase
python scripts/prepare_knbc.py KNBC_v1.0_090925_utf8 --granularity=tag
python scripts/prepare_knbc.py KNBC_v1.0_090925_utf8 --granularity=word
```
=> Add granularity option to prepare_knbc.py

javascript/src/cli.ts, javascript/src/dom.ts, javascript/src/html_processor.ts, javascript/src/index.ts, javascript/src/parser.ts
Use `@return` instead of `@returns` to align with [Google TypeScript Style Guide](https://google.github.io/styleguide/tsguide.html)
=> Rename @returns to @return

tests/test_quality.py
This change enables the unit test to report all failing cases, not just the first one encountered.
=> Show failing sentences for quality test

javascript/src/html_processor.ts
Chrome recently shipped two changes to the CSS `display` property.
* [crbug.com/995106]: Support multi-keyword syntax for the display property
* [crbug.com/880802]: Support ruby-specific display values; ruby and ruby-text
This patch supports the change.
Fixes #476.
[crbug.com/995106]: http://crbug.com/995106
[crbug.com/880802]: http://crbug.com/880802
=> Support new CSS `display` syntax

.github/workflows/py-unittest.yml, budoux/main.py, setup.cfg
Context: https://setuptools.pypa.io/en/latest/pkg_resources.html
> Use of pkg_resources is deprecated in favor of [importlib.resources](https://docs.python.org/3.11/library/importlib.resources.html#module-importlib.resources), [importlib.metadata](https://docs.python.org/3.11/library/importlib.metadata.html#module-importlib.metadata) and their backports ([importlib_resources](https://pypi.org/project/importlib_resources), [importlib_metadata](https://pypi.org/project/importlib_metadata)). Some useful APIs are also provided by [packaging](https://pypi.org/project/packaging) (e.g. requirements and version parsing). Users should refrain from new usage of pkg_resources and should work to port to importlib-based solutions.
=> Replace pkg_resources with importlib_resources

javascript/package-lock.json, javascript/package.json
This change suppresses the punycode depracation warning in BudouX Node.js.
Context: https://github.com/jsdom/jsdom/issues/3613
=> [nodejs] Override with tough-cookie@5.0.0-rc.4 to suppress punycode deprecation warning

README.md
Due to frequent inquiries about Korean language support, we're adding a description of the tentative solution using `word-break: keep-all`.
=> Mention Korean support in README.md

java/src/main/java/com/google/budoux/HTMLProcessor.java, java/src/test/java/com/google/budoux/HTMLProcessorTest.java
Current Java code does not work with HTML strings that have comment nodes, throwing the following error.
```
java.util.NoSuchElementException
at java.base/java.util.ArrayDeque.removeFirst(ArrayDeque.java:363)
at java.base/java.util.ArrayDeque.pop(ArrayDeque.java:594)
at com.google.budoux.HTMLProcessor$PhraseResolvingNodeVisitor.tail(HTMLProcessor.java:163)
at org.jsoup.select.NodeTraversor.traverse(NodeTraversor.java:59)
at org.jsoup.nodes.Node.traverse(Node.java:707)
at org.jsoup.nodes.Element.traverse(Element.java:1883)
at com.google.budoux.HTMLProcessor.resolve(HTMLProcessor.java:194)
```
This PR fixes this issue by ignoring comment nodes in the node visitor.
=> [Java] Handle comment nodes

java/src/main/java/com/google/budoux/HTMLProcessor.java, java/src/test/java/com/google/budoux/HTMLProcessorTest.java
Current Java code throws the following error when the input HTML has a skip node at the end. This PR fixes the issue.
```
java.lang.StringIndexOutOfBoundsException: index 15,length 15
at java.base/java.lang.String.checkIndex(String.java:3278)
at java.base/java.lang.StringUTF16.checkIndex(StringUTF16.java:1470)
at java.base/java.lang.StringUTF16.charAt(StringUTF16.java:1267)
at java.base/java.lang.String.charAt(String.java:695)
at com.google.budoux.HTMLProcessor$PhraseResolvingNodeVisitor.head(HTMLProcessor.java:133)
at org.jsoup.select.NodeTraversor.traverse(NodeTraversor.java:34)
at org.jsoup.nodes.Node.traverse(Node.java:707)
at org.jsoup.nodes.Element.traverse(Element.java:1883)
at com.google.budoux.HTMLProcessor.resolve(HTMLProcessor.java:194)
```
=> [Java] Skip node at the end of input

java/pom.xml
Force update maven-javadoc-plugin to resolve the error mentioned in #773 
We keep using the same parent pom.xml for now to minimize the gap between the past artifacts.
It also updates the Java port version to override the misconfigured v0.6.3 release.
=> Use updated maven-javadoc-plugin

javascript/src/tests/test_webcomponents.ts, javascript/src/webcomponents/budoux-base.ts
Fix #811 
Using `setInnerHtml`, which modifies the DOM tree dynamically, prevents BudouX Web Component from working correctly with [Lit](https://lit.dev/). 
Following the guidance from https://github.com/lit/lit/issues/4834#issuecomment-2480244632, this change allows BudouX Web Component to update its content with BudouX parser's `applyToElement`, which only modifies `textContent`.
=> Make BudouX Web Components work without setInnerHtml

javascript/README.md
Adding a note which explains that Web Components may introduce duplicated ZWSPs and why it should not be a problem.
=> Add notes on Web Components

javascript/src/html_processor.ts
Use user-defined type guards to handle Node vs string in a more IDE-friendly way.
=> Add type guards for NodeOrText

scripts/finetune.py, scripts/train.py
The latest mypy and jax combination yields the typing error as below. This fixes the issue by making it sure that the epsilon is a float.
```
scripts/train.py:26: error: Incompatible types in assignment (expression has
type "floating[Any]", variable has type "float")  [assignment]
EPS: float = jnp.finfo(float).eps
^~~~~~~~~~~~~~~~~~~~
scripts/finetune.py:30: error: Incompatible types in assignment (expression has
type "floating[Any]", variable has type "float")  [assignment]
EPSILON: float = jnp.finfo(float).eps
^~~~~~~~~~~~~~~~~~~~
Found 2 errors in 2 files (checked 23 source files)
```
=> Fix python typing issue

budoux/main.py
This CL adds an option to change the phrase delimiter, from the default `\n` to the user specified string.
Example:
```sh
% budoux -D ' / ' 私の名前は中野です
私の / 名前は / 中野です
```
Fixed #793.
=> Add the `--phrase-delimiter` option to the Python command line

javascript/package.json
This PR improves the package distribution of Budoux to enhance compatibility and usability in various JavaScript environments.
Specifically, it addresses the following:
*   **Node.js ESM Support:** Previously, the build process for ESM would incorrectly overwrite `win.ts` with `win-browser.ts`. This prevented Node.js environments from using the ESM build, as `win-browser.ts` relies on browser-specific APIs. This change ensures that Node.js can properly import and use the ESM version of Budoux.
*   **Enhanced Package Resolution with `exports` Field:** The addition of the `exports` field in `package.json` provides explicit mappings for different module formats (CommonJS and ESM). This improves interoperability with modern JavaScript bundlers and frameworks, ensuring they correctly resolve …
=> Add exports in package.json

javascript/package.json, javascript/src/dom.ts, javascript/src/tests/test_html_processor.ts, javascript/src/tests/testutils-browser.ts, javascript/src/tests/testutils.ts
Isolate DOM related functions used only by tests into `testutils.ts`, making the original `dom.ts` and `dom-browser.ts` as small as possible. By doing this, the product code don't need to worry about risky functions such as `setInnerHTML`.
=> Isolate functions only used by tests

javascript/src/html_processor.ts
In preparation for v0.7.0 release, I'm deleting the deprecated function that is scheduled to be removed.
=> Delete the deprecated `applyElement` function
