google/budoux

README.md
fix from master branch to main branch.
=> Fix link to the JavaScript module documentation.

.github/workflows/py_unittest.yml
=> add: unittest CI for Python

budoux/feature_extractor.py, tests/test_feature_extractor.py
=> Fix: encoding error in windows

README.md
For convenience, added badges shows its latest version as image and links repo with the project pages of PyPI and npm.
[![PyPI](https://img.shields.io/pypi/v/budoux?color=blue)](https://pypi.org/project/budoux/) [![npm](https://img.shields.io/npm/v/budoux?color=yellow)](https://www.npmjs.com/package/budoux)
=> Add badges (PyPI, npm)

.github/workflows/nodejs-unittest.yml, .github/workflows/py-unittest.yml, .github/workflows/style-check.yml
I added a `pull_request` trigger to make CI work for PR commits.
=> Add PR trigger to CI

javascript/src/cli.ts, javascript/tests/test_cli.ts
=> Add thres parameter to Node.js CLI

javascript/src/webcomponents/budoux-base.ts, javascript/src/webcomponents/budoux-ja.ts, javascript/src/webcomponents/budoux-zh-hans.ts
Refactor Japanese and Simplified Chinese Web components to share the same base component.
=> Add the base BudouX Web component

.github/workflows/style-check.yml, scripts/train.py
- Simplify the mypy check
- Fix some mypy issues
=> Fix Mypy GitHub Action

demo/package-lock.json, javascript/package-lock.json, javascript/package.json, javascript/src/cli.ts, javascript/src/parser.ts, javascript/src/tests/test_parser.ts
=> Remove P features from JS module

README.md, scripts/prepare_knbc.py
=> Remove tar module dependency

java/src/test/java/com/google/budoux/ParserTest.java
Change-Id: Ic8c7d6b2b1af7026af74f2a450b4056d337b5c16
=> Java style fix

.github/workflows/py-unittest.yml, .github/workflows/style-check.yml, scripts/finetune.py, scripts/train.py, setup.cfg
- Fix JAX and mypy versions
- Drop Python 3.7 support
- Fix type issues
=> Fix Python dependency issues

javascript/src/tests/test_webcomponents.ts, javascript/src/webcomponents/budoux-base.ts
Fix #280 and possibly #284
I would like to wait merging this until #290 is resolved.
=> [Web Components] Use Light DOM instead of Shadow DOM

.github/workflows/style-check.yml
Update the hash to the one equivalent to `v3`.
=> Update Google Java Format action

java/src/main/java/com/google/budoux/HTMLProcessor.java
Implement the tail function for the Textize node visitor for the backward compatibility with older versions of jsoup.
=> Implement tail for node visitor

java/pom.xml
Update jsoup to the latest version.
=> Update jsoup to 1.16.2

README.md, budoux/__init__.py, java/README.md, javascript/README.md
Also, expose `load_default_thai_parser` in `budoux/__init__.py`.
=> Update README for Thai support

demo/static/index.html
Replace the WBR label with ZWSP in the Demo page to represent the actual mechanism of BudouX.
=> Replace WBR with ZWSP in demo page

demo/src/app.ts
This change will make it easy to share the demo page with specific use cases embedded.
(e.g. https://google.github.io/budoux/?q=今日はいい天気です)
=> [demo] Bind the input content and the query param

.github/workflows/style-check.yml
=> Update Node.js to v20 in style-check.yml

budoux/__init__.py, bump_version.py, java/pom.xml, javascript/package-lock.json, javascript/package.json, javascript/src/cli.ts
Adding a script to update the version number across multiple lang ports.
=> Bump to 0.6.3

javascript/src/dom.ts, javascript/src/html_processor.ts, javascript/src/webcomponents/budoux-base.ts
This is an effort to make `dom.ts` smaller and the dependencies simpler.
=> Move applyWrapStyle to html_processor.ts

javascript/src/cli.ts, javascript/src/tests/test_cli.ts
=> Add sep option to JavaScript CLI
